### ISSUE TITLE
Απορίες

### ISSUE THREAD

**Issue by epidrome** [upatras-hci/iv#2]
Σε αυτήν την περιοχή μπορείτε να στέλνετε γενικές απορίες σχετικά με το μάθημα.

Αν το ερώτημα σχετίζεται με μια συγκεκριμένη εργασία θα πρέπει να το στείλετε στα θέματα στο αντίστοιχο αποθετήριο της εργασίας ή αν σχετίζεται μόνο με το προσωπικό σας αποθετήριο μπορείτε να ανοίξετε εκεί θέμα κάνοντας μενσιον τον καθηγητή. Για πολύπλοκα ερωτήματα συνήθως είναι καλύτερα να γίνεται συζήτηση στην τάξη με διαμοιρασμό οθόνης.

[Οδηγίες για την χρήση των issues-notifications](https://guides.github.com/features/issues/)

**Comment by irozg** [comment]
Καλησπέρα, για την επόμενη άσκηση, μπορώ να χρησιμοποιήσω το github pages αντί για το netfly; Ευχαριστώ

**Comment by epidrome** [comment]
για το βιογραφικό;
https://courses-ionio.github.io/projects/cv/
η εκφώνηση λέει ότι θες!

η ιστοσελίδα του βιβλίου παίζει μόνο σε νετλιφαη

**Comment by irozg** [comment]
ερώτηση 2: το αρχείο yaml, πρεπει να είναι ένα ή μπορουμε να το σπάσουμε σε πολλά;

**Comment by epidrome** [comment]
σε κάποια μορφότυπα είναι ένα αλλού είναι πολλά, ότι θέλετε!

**Comment by skartz0** [comment]
Καλησπέρα, είχα κλείσει ενα meeting χτες, με μόνη διαθεσιμότητα σήμερα, αλλα το λινκ για το zoom φαίνεται να μη λειτουργεί τώρα που προσπαθώ να συνδεθώ

**Comment by epidrome** [comment]
ναι γιατί έγινε μεταφορά της συνάντησης την Πεμ. 8μμ, οι συναντήσεις κατά προτίμηση γίνονται τις ώρες του μαθήματος

**Comment by moya10** [comment]
Καλές γιορτές..

**Comment by skartz0** [comment]
καλα χριστούγεννα!!

**Comment by irozg** [comment]
Καλή χρονία! ερώτηση πότε παραδίδουμε το report; Ευχαριστώ!

**Comment by epidrome** [comment]
καλή χρονιά!

σύμφωνα με το πρόγραμμα,

την 12η εβδομάδα

δλδ τέλος Ιαν

**Comment by irozg** [comment]
Καλησπέρα σας, 

οι βαθμοί δεν έχουν περαστεί στο progress, ούτε ως προσωρινοί και δεν ξέρουμε καν αν περάσαμε. Μήπως υπάρχει κάποιο τεχνικό θέμα;

Ευχαριστώ πολύ!

**Comment by epidrome** [comment]
πράγματι υπάρχει μια ασάφεια για το πως θα στείλω του βαθμούς

ο διευθυντής μου είπε να στείλω στο τμήμα με ημεηλ

το τμήμα μου είπε να μιλήσω με τα δίκτυα για αν ανοίξω λογαριασμό

τα δίκτυα δεν μου απάντησαν στο ερώτημα-αίτημα μου

ευχαριστώ για την υπενθύμιση θα τους στείλω στο τμήμα και ας κάνουν ότι νομίζουν!
